# Generated by Django 5.1.5 on 2025-02-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('normalized_name', models.CharField(editable=False, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('records_processed', models.IntegerField()),
                ('errors', models.TextField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodreads_book_id', models.IntegerField(blank=True, null=True)),
                ('best_book_id', models.IntegerField(blank=True, null=True)),
                ('work_id', models.IntegerField(blank=True, null=True)),
                ('books_count', models.IntegerField(default=1)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True)),
                ('isbn13', models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True)),
                ('original_publication_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('original_title', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('average_rating', models.FloatField(blank=True, db_index=True, null=True)),
                ('ratings_count', models.IntegerField(blank=True, db_index=True, null=True)),
                ('work_ratings_count', models.IntegerField(blank=True, null=True)),
                ('work_text_reviews_count', models.IntegerField(blank=True, null=True)),
                ('ratings_1', models.IntegerField(blank=True, null=True)),
                ('ratings_2', models.IntegerField(blank=True, null=True)),
                ('ratings_3', models.IntegerField(blank=True, null=True)),
                ('ratings_4', models.IntegerField(blank=True, null=True)),
                ('ratings_5', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('small_image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='books', to='books.author')),
            ],
        ),
    ]
